openapi: 3.0.4
info:
  title: FoodDeliveryAPI
  description: |-
    Вариант 8. Сервис доставки еды.
    Сущности: Restaurant, Dish, Order, Courier.
    Функциональность:
      1. Меню ресторанов.
      2. Оформление заказа.
      3. Оплата.
      4. Отслеживание доставки.
      5. Оценки блюд и ресторанов.
      6. Связь с курьером (чат).
      7. Повтор заказа.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Example Server
tags:
  - name: Restaurant
    description: Restaurant and Menu Operations
  - name: Dish
    description: Information about dishes
  - name: Order
    description: Order processing and management
  - name: Payment
    description: Payments
  - name: Courier
    description: Couriers and tracking
  - name: Rating
    description: Ratings of dishes and restaurants
  - name: User
    description: Users and order history

paths:
  /restaurants:
    get:
      tags:
        - Restaurant
      summary: List of restaurants
      description: Get list of restaurants
      parameters:
        - name: query
          in: query
          description: Search bar
          schema:
            type: string
        - name: lat
          in: query
          schema:
            type: number
            format: double
        - name: lng
          in: query
          schema:
            type: number
            format: double
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: List of restaurants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Restaurant'
        '500':
          $ref: '#/components/responses/InternalError'

  /restaurants/{restaurantId}/menu:
    get:
      tags:
        - Restaurant
      summary: Restaurant menu
      parameters:
        - name: restaurantId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Menue
          content:
            application/json:
              schema:
                type: object
                properties:
                  dishes:
                    type: array
                    items:
                      $ref: '#/components/schemas/Dish'
        '404':
          $ref: '#/components/responses/NotFound'

  /dishes/{dishId}:
    get:
      tags:
        - Dish
      summary: Dish details
      parameters:
        - name: dishId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Dish information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dish'
        '404':
          $ref: '#/components/responses/NotFound'

  /orders:
    post:
      tags:
        - Order
      summary: Create order
      description: Creates an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreate'
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /orders/{orderId}:
    get:
      tags:
        - Order
      summary: Get order by id
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      tags:
        - Order
      summary: partially change order, update status
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tip_cents:
                  type: integer
                delivery_address:
                  $ref: '#/components/schemas/Address'
      responses:
        '200':
          description: Updated order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          $ref: '#/components/responses/BadRequest'

  /orders/{orderId}/cancel:
    post:
      tags:
        - Order
      summary: Cancel order
      description: depends from canselation rules
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order canceled
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          description: Cannot be canceled

  /orders/{orderId}/reorder:
    post:
      tags:
        - Order
      summary: Reorder
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: New order created based on old one
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '409':
          description: Error (for ex. dishes are unavailable)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /orders/{orderId}/status:
    get:
      tags:
        - Order
      summary: Current order status
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Current status and brief information about the courier
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  courier:
                    $ref: '#/components/schemas/Courier'
        '404':
          $ref: '#/components/responses/NotFound'

  /couriers/{courierId}/location:
    post:
      tags:
        - Courier
      summary: The courier sends a location update.
      parameters:
        - name: courierId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocationWithTimestamp'
      responses:
        '200':
          description: Location saved
        '400':
          $ref: '#/components/responses/BadRequest'

  /orders/{orderId}/messages:
    post:
      tags:
        - Order
      summary: Send a message to the order chat
      security:
        - bearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - from
                - text
              properties:
                from:
                  type: string
                  enum: [user,courier,system]
                text:
                  type: string
      responses:
        '201':
          description: Massage send
        '400':
          $ref: '#/components/responses/BadRequest'

  /payments:
    post:
      tags:
        - Payment
      summary: Create payment intent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '201':
          description: Payment intent сcreated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentIntent'
        '422':
          description: Payment declined
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /ratings:
    post:
      tags:
        - Rating
      summary: Add a rating (dish or restaurant)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RatingCreate'
      responses:
        '201':
          description: Rating saved
        '400':
          $ref: '#/components/responses/BadRequest'

  /restaurants/{restaurantId}/ratings:
    get:
      tags:
        - Rating
      summary: Get restaraunt rating
      parameters:
        - name: restaurantId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Rating list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rating'

  /dishes/{dishId}/ratings:
    get:
      tags:
        - Rating
      summary: Get dish ratings
      parameters:
        - name: dishId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Rating list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rating'

  /users:
    post:
      tags:
        - User
      summary: Create a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users/{userId}/orders:
    get:
      tags:
        - User
      summary: User order history
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    BadRequest:
      description: Неверный запрос
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Restaurant:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        location:
          $ref: '#/components/schemas/Location'
        rating:
          type: number
          format: float
        minimum_order_cents:
          type: integer
        delivery_fee_cents:
          type: integer
        open_now:
          type: boolean
      required:
        - id
        - name

    RestaurantUpdate:
      type: object
      properties:
        name:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        open_now:
          type: boolean
        delivery_fee_cents:
          type: integer


    Dish:
      type: object
      properties:
        id:
          type: string
        restaurant_id:
          type: string
        name:
          type: string
        description:
          type: string
        price_cents:
          type: integer
        currency:
          type: string
          default: "BYN"
        available:
          type: boolean
        rating:
          type: number
          format: float

    Address:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        lat:
          type: number
          format: double
        lng:
          type: number
          format: double

    Location:
      type: object
      properties:
        lat:
          type: number
          format: double
        lng:
          type: number
          format: double

    LocationWithTimestamp:
      type: object
      properties:
        lat:
          type: number
          format: double
        lng:
          type: number
          format: double
        speed:
          type: number
          format: float
        timestamp:
          type: string
          format: date-time
      required:
        - lat
        - lng
        - timestamp

    OrderCreate:
      type: object
      properties:
        user_id:
          type: string
        restaurant_id:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        delivery_address:
          $ref: '#/components/schemas/Address'
        payment_method:
          type: string
          enum: [card, cash_on_delivery]
        tip_cents:
          type: integer
      required:
        - user_id
        - restaurant_id
        - items
        - delivery_address

    OrderItem:
      type: object
      properties:
        dish_id:
          type: string
        quantity:
          type: integer
          minimum: 1
      required:
        - dish_id
        - quantity

    Order:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        restaurant_id:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        subtotal_cents:
          type: integer
        delivery_fee_cents:
          type: integer
        tip_cents:
          type: integer
        total_cents:
          type: integer
        status:
          enum: [created, accepted_by_restaurant, preparing, ready_for_pickup, courier_assigned, on_the_way, picked_up, delivered, cancelled, failed]
          description: |
            Possible statuses: created, accepted_by_restaurant, preparing, ready_for_pickup,
            courier_assigned, on_the_way, picked_up, delivered, cancelled, failed
        payment_status:
          type: string
          description: pending, authorized, succeeded, failed, refunded
        courier:
          $ref: '#/components/schemas/Courier'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Courier:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        phone:
          type: string
        location:
          $ref: '#/components/schemas/LocationWithTimestamp'
        status:
          type: string
          description: offline, available, assigned, delivering, on_break

    UserCreate:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'
      required:
        - name
        - email

    User:
      allOf:
        - $ref: '#/components/schemas/UserCreate'
        - type: object
          properties:
            id:
              type: string

    RatingCreate:
      type: object
      properties:
        user_id:
          type: string
        target_type:
          type: string
          enum: [dish, restaurant]
        target_id:
          type: string
        score:
          type: integer
          minimum: 0
          maximum: 10
        comment:
          type: string
      required:
        - user_id
        - target_type
        - target_id
        - score

    Rating:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        target_type:
          type: string
        target_id:
          type: string
        score:
          type: integer
        comment:
          type: string
        created_at:
          type: string
          format: date-time

    PaymentRequest:
      type: object
      properties:
        order_id:
          type: string
        amount_cents:
          type: integer
        currency:
          type: string
          default: "BYN"
        payment_method:
          type: string
      required:
        - order_id
        - amount_cents

    PaymentIntent:
      type: object
      properties:
        id:
          type: string
        client_secret:
          type: string
        status:
          type: string
        amount_cents:
          type: integer
        currency:
          type: string

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
